### PR TITLE
Remove default experimental repo

### LINKED ISSUE #762: Make sure server starts if no internet connection
From the logs

Downloading package metadata from URL [http://skipper-repository.cfapps.io/repository/experimental/index.yml]

In PCF environments outside internet access maybe disabled.  The server should start in anycase even if it can't fine a configured remote package repository.

### PR DESCRIPTION
**Pull request by jvalkeal**
- Remove experimental remote sample repo from a default
  configuration and document how to add it back. This should
  allow server to start with access to internet.
- Fixes #762

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Looks like there are some build failure from travis ci:

```
[ERROR] Failures: 
[ERROR]   StateMachineTests.testUpgradeCancelWhileCheckingApps:439 expected:<INITIAL> but was:<null>
[INFO] 
[ERROR] Tests run: 103, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] --------------------
```

Not sure if this is related to removing the experimental repo.

**Comment by jvalkeal** [comment]
Probably unrelated as local build is fine.

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Merged as d7f9baf

**Pull request closed without merging**
