### PR TITLE
Use Spring Cloud Kubernetes to read ConfigMap

### LINKED ISSUE #792: Use Spring Cloud Kubernetes to read ConfigMap
Add Spring Cloud Kubernetes dep to load properties from the application.yaml config block from a k8s ConfigMap.

Relates to https://github.com/spring-cloud/spring-cloud-dataflow/issues/2735

### PR DESCRIPTION
**Pull request by chrisjs**
Resolves #792

### CODE REVIEW

**Comment by jvalkeal** [comment]
If only thing what this brings into skipper is `ConfigReloadAutoConfiguration` I don't find it very useful, unless I'm missing something. I'm expecting whole skipper to blow up if running context is refreshed?

**Comment by jvalkeal** [comment]
Ah it's `BootstrapConfiguration` which gets created automatically and that exception comes from there and I see same with dataflow. I'm not exactly happy about `spring-cloud-kubernetes-config` as its default functionality is way too intrusive.

**Comment by chrisjs** [comment]
its being used to read boot properties from a k8s `ConfigMap`, for example:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/801faa8d9bbcf3c2a6c267660e3ebb4aa6051536/src/kubernetes/skipper/skipper-config-kafka.yaml#L8

while the same is being done in dataflow the main motivator for using it here as well was the account syntax being used -- for example `_[default]_` isn't a valid pattern for a container env var as the regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'). that would leave us with stuffing things into SAJ which can get a bit out of hand.

**Comment by jvalkeal** [comment]
Merged per c2838cee2757d688ce337c41495331a5a6266ef0

**Pull request closed without merging**
