### PR TITLE
Create Repository entity and supporting Spring Data REST scaffolding

### LINKED ISSUE #29: Create Repository entity + supporting CRUD operations
A Repository entity represents a location to download package information.  It refers to a location to obtain an index file of all packages hosted by that repository.  

Expose via Spring Data REST for CRUD.

Do not consider keyfiles/sha hashes etc.

### PR DESCRIPTION
**Pull request by markpollack**
* Fixed failing Shell test by excluding spring data jpa in pom

* Fixes #29

### CODE REVIEW

**Comment by markpollack** [comment]
In our discussion, you didn't have any comments on this, so I will merge so I can continue to make progress on other issues that build upon this one.

**Comment by markpollack** [comment]
actually travis failed due to bad assumption about the `~.skipper` directory

```
[ERROR] Errors: 
[ERROR]   PackageIndexLoaderTests.cleanPackageIndexDir:59 » NoSuchFile /home/travis/.ski...
[INFO] 
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0
```
will fix on merge.

**Comment by markpollack** [comment]
squashed and merged as cfc1374380dbdca8d9ee386aacbbc3b6cdfbdd35

**Comment by ilayaperumalg** [comment]
@markpollack thanks for merging. It looked good to me. I only had questions around the use cases around accessing the Repository which would be done in the upcoming stories.

**Comment by ilayaperumalg** [comment]
oh, the travis build failure; didn't notice that one since the local build passed for me.

**Pull request closed without merging**
