### PR TITLE
Generate stubs using `spring-cloud-contract-wiremock`

### PR DESCRIPTION
**Pull request by eddumelendez**
Resolves spring-cloud/spring-cloud-skipper#165

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@eddumelendez Thank you for the contribution. With the mocks in place, do you think we can avoid running the real tests and manual entries of response fields in the REST documentation now?

For instance, you can check this one: https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/RollbackDocumentation.java#L60

**Comment by eddumelendez** [comment]
@ilayaperumalg do you mean doing something like this?

```java
this.mockMvc.perform(
			post("/api/rollback/{releaseName}/1", releaseName)).andDo(print())
				.andExpect(status().isCreated())
				.andDo(WireMockRestDocs.verify().stub("rollback-documentation/rollback-release"));
```

**Comment by eddumelendez** [comment]
@ilayaperumalg indeed, it will not be replaced. ATM, stubs will be generated but not use it. Perhaps, they can be use it for contract testing in `spring-cloud-skipper-client`?

**Comment by ilayaperumalg** [comment]
@eddumelendez ok, that would be a good choice to test at the client. But, I was hoping to replace this manual need to update the response field (as a change in one attribute triggers a change in here as well). I would like to know if you have any suggestion on it. Thank you!

**Comment by eddumelendez** [comment]
Well, given the configuration below the documentation is always generated with the response

https://github.com/spring-cloud/spring-cloud-skipper/blob/cc9c8b7000d2db4e4004be262c7b8b635b06a3c6/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/BaseDocumentation.java#L78-L84

The missing part will be the field´s description.

**Comment by ilayaperumalg** [comment]
Closing this PR in favor of https://github.com/spring-cloud/spring-cloud-skipper/pull/673. 

Thank you @eddumelendez for the contribution! Your PR changes are applied into #673 with the changes to have mocks for the tests inside the documentation generation classes.

**Pull request closed without merging**
