### PR TITLE
fail fast on bad cloud foundry platform (fixes #555)

### LINKED ISSUE #555: CloudFoundryPlatformAutoConfiguration::createAndSaveCFAppDeployer null return value
While setting up a `skipper` server, I accidentally omitted a cloud foundry account password.

This is caught here https://github.com/spring-cloud/spring-cloud-skipper/blob/36be4df251ab5178a1dbd24737aae3831ddf0b45/spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryPlatformAutoConfiguration.java#L128-L132

and a null value is added to the list of deployers here:
https://github.com/spring-cloud/spring-cloud-skipper/blob/36be4df251ab5178a1dbd24737aae3831ddf0b45/spring-cloud-skipper-platform-cloudfoundry/src/main/java/org/springframework/cloud/skipper/deployer/cloudfoundry/CloudFoundryPlatformAutoConfiguration.java#L65-L70

That null bean is propagated to the `DeployerInitializationService` where it blows up when it tries to save a null deployer.
https://github.com/spring-cloud/spring-cloud-skipper/blob/36be4df251ab5178a1dbd24737aae3831ddf0b45/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/DeployerInitializationService.java#L53-L63

Instead of catching the exception and returning the null value, it should probably fail fast.

### PR DESCRIPTION
**Pull request by Fitzoh**
Also fix formatting of log message (no space after 'account')

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
LGTM, If there are no objections on failing fast (during the server startup) in this case I can go ahead and merge this.

**Comment by ilayaperumalg** [comment]
@Fitzoh Could you fix the build failure (I guess some checkstyle issue)?

**Comment by Fitzoh** [comment]
Looks like we got past checkstyle ¯\\\_(ツ)_/¯

**Comment by ilayaperumalg** [comment]
LGTM, merging. @Fitzoh Thank you for the contribution!

**Comment by ilayaperumalg** [comment]
Rebased and merged as a0d4fe7

**Pull request closed without merging**
