### PR TITLE
gh-124 Add RESTDocs based documentation

### PR DESCRIPTION
**Pull request by ghillert**
* RestDoc tests are run as part of the `spring-cloud-skipper-server` tests

resolves https://github.com/spring-cloud/spring-cloud-skipper/issues/124

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@ghillert There are checkstyle errors (especially the package import order on the files). I went ahead and fixed them. But, I see some test failures:

```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 22.684 s <<< FAILURE! - in org.springframework.cloud.skipper.controller.docs.PackageMetadataDocumentation
[ERROR] getPackageMetadataDetails(org.springframework.cloud.skipper.controller.docs.PackageMetadataDocumentation)  Time elapsed: 7.134 s  <<< ERROR!
org.springframework.restdocs.snippet.SnippetException: Fields with the following paths were not found in the payload: [appVersion]
	at org.springframework.cloud.skipper.controller.docs.PackageMetadataDocumentation.getPackageMetadataDetails(PackageMetadataDocumentation.java:84)

[ERROR] getAllPackageMetadata(org.springframework.cloud.skipper.controller.docs.PackageMetadataDocumentation)  Time elapsed: 5.376 s  <<< ERROR!
org.springframework.restdocs.snippet.SnippetException: Fields with the following paths were not found in the payload: [_embedded.packageMetadata[].appVersion]
	at org.springframework.cloud.skipper.controller.docs.PackageMetadataDocumentation.getAllPackageMetadata(PackageMetadataDocumentation.java:48)
```

**Comment by dsyer** [comment]
How about generating stubs as well (you only need to add spring-cloud-contract-wiremock)?

**Comment by ghillert** [comment]
@ilayaperumalg 

* Fixed tests
* Fixed Checkstyle issues
* Rebased with Master

**Comment by ilayaperumalg** [comment]
@ghillert what do you think about this: https://github.com/spring-cloud/spring-cloud-skipper/pull/160#issuecomment-335383596

**Comment by ilayaperumalg** [comment]
Created https://github.com/spring-cloud/spring-cloud-skipper/issues/165 to track @dsyer's suggestion on using spring-cloud-contract-wiremock.

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as ab7d0ede1dc5d6abd03d4f68ef4d3ef4f017b10c along with a refactoring of moving test classes into `server` packages abdcb0e3b7ea7971d04cd2041ca0dfc39637213a

**Pull request closed without merging**
